spring:
  application:
    name: 'discovery-service'
  main:
    banner-mode: 'off'
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: 'localhost'
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true